name: E2E Tests

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm run start &
        env:
          CI: true

      - name: Wait for application to be ready
        run: |
          npx wait-on https://isaaclins.com/SECRET/ --timeout 60000

      - name: Check application logs
        run: |
          echo "Checking application logs..."
          ps aux | grep node

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: https://isaaclins.com/SECRET/